# Generated by Django 5.1.6 on 2025-07-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Jina la Vifaa')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Idadi Jumla')),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('maintenance', 'Under Maintenance')], default='available', max_length=20, verbose_name='Hali')),
                ('functional', models.PositiveIntegerField(default=0, verbose_name='Imara')),
                ('broken', models.PositiveIntegerField(default=0, verbose_name='Vibovu')),
                ('need', models.CharField(blank=True, max_length=255, verbose_name='Uhitaji')),
                ('need_quantity', models.PositiveIntegerField(default=0, verbose_name='Idadi ya Uhitaji')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Gharama')),
                ('action', models.CharField(choices=[('repair', 'Repair'), ('replace', 'Replace'), ('order', 'Order More'), ('none', 'None')], default='none', max_length=20, verbose_name='Hatua')),
            ],
        ),
    ]
