# Generated by Django 5.1.6 on 2025-08-17 02:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='title')),
                ('dateOfAnalysis', models.DateField(blank=True, null=True, verbose_name='date of analysis')),
                ('AssetName', models.CharField(blank=True, max_length=20, null=True, verbose_name='asset name')),
                ('totalNumberOfAssets', models.IntegerField(verbose_name='total number of assets')),
                ('abledAssetsNumber', models.IntegerField(verbose_name='total number of abled assets')),
                ('disabledAssetsNumber', models.IntegerField(verbose_name='total number of disabled assets')),
                ('isRequired', models.CharField(choices=[('is required', 'is required'), ('not required', 'Not required')], max_length=20, verbose_name='is required?')),
                ('perCost', models.IntegerField(null=True, verbose_name='cost per asset')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='api.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Department asset',
                'verbose_name_plural': 'Department Assets',
                'ordering': ['title', 'department'],
                'indexes': [models.Index(fields=['department', 'dateOfAnalysis'], name='api_departm_departm_d39f41_idx')],
            },
        ),
    ]
