# Generated by Django 5.1.6 on 2025-08-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(default='BAHI SDA', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('message sent successfully', 'Message Sent')], default='pending', max_length=40),
        ),
    ]
