# Generated by Django 5.1.6 on 2025-08-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_departmentassets'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='departmentassets',
            name='api_departm_departm_d39f41_idx',
        ),
        migrations.AlterField(
            model_name='departmentassets',
            name='isRequired',
            field=models.CharField(choices=[('is required', 'is required'), ('not required', 'not required')], max_length=20, null=True, verbose_name='is required?'),
        ),
        migrations.AddIndex(
            model_name='departmentassets',
            index=models.Index(fields=['department', 'AssetName'], name='api_departm_departm_aa8fbd_idx'),
        ),
    ]
