# Generated by Django 5.1.6 on 2025-07-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeaconSupportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Jina kamili')),
                ('description', models.TextField(blank=True, verbose_name='Maelezo')),
                ('assisted_people', models.PositiveIntegerField(default=0, verbose_name='Waliosaidiwa')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Kiasi')),
                ('prayed_for', models.TextField(blank=True, verbose_name='Ulio waombea')),
                ('challenge_type', models.CharField(max_length=255, verbose_name='Aina ya changamoto')),
                ('people_prayed_for', models.PositiveIntegerField(default=0, verbose_name='Watu walioombewa')),
                ('date', models.DateField(verbose_name='Tarehe')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('ongoing', 'Ongoing')], default='pending', max_length=50, verbose_name='Hali')),
                ('action', models.TextField(blank=True, verbose_name='Hatua')),
            ],
        ),
    ]
