# Generated by Django 5.1.6 on 2025-08-19 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_message_sender_message_sender_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender_name',
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('message sent successfully', 'message  Sent')], default='pending', max_length=40),
        ),
    ]
