# Generated by Django 5.1.6 on 2025-08-17 15:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_departmentassets_api_departm_departm_d39f41_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Order Title')),
                ('dateCreated', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('dateToImplement', models.DateField(verbose_name='Implementation Deadline')),
                ('howToImplement', models.TextField(verbose_name='Implementation Instructions')),
                ('Requirements', models.TextField(verbose_name='Requirements')),
                ('costToImplement', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Implementation Cost')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Order Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Department Order',
                'verbose_name_plural': 'Department Orders',
                'ordering': ['-dateCreated'],
                'indexes': [models.Index(fields=['department', 'status'], name='api_departm_departm_24626a_idx')],
            },
        ),
    ]
