# Generated by Django 5.1.6 on 2025-08-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_message_sender_message_sender_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender_name',
            new_name='sender',
        ),
    ]
