# Generated by Django 5.1.6 on 2025-08-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_message_sender_alter_message_status'),
    ]

    operations = [
    ]
