# Generated by Django 5.1.6 on 2025-08-19 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_message_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'Regular User'), ('manager', 'Manager')], default='user', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_update', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
